version: '3'
services:
  quizservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quizservice
    restart: always
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://embedded-system-huynhndev0403-977f.f.aivencloud.com:16259/embeddedSys
      - SPRING_DATASOURCE_USERNAME=avnadmin
      - SPRING_DATASOURCE_PASSWORD=AVNS_eVe4BBP9cLtkV8qBrsp
    ports:
      - "8085:8085"
  mysqldb:
    image: mysql:8.0.33
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=embeddedSys
    volumes:
      - mysql_embeddedSys:/var/lib/mysql
volumes:
  mysql_embeddedSys: